Repository hypothesis/h, pull requests merged in 2018-07, with the labels that each got.

#5102 DB migration to make user.email nullable
  h/migrations/versions/792debe852c3_make_user_email_nullable.py
Labels: lms

#5119 Don't send reply notifications to users with no email
  h/notification/reply.py
  tests/h/notification/reply_test.py
Labels: lms

#5125 Add test for `DeletedFilter`
  h/search/index.py
  tests/h/search/old_index_test.py
  tests/h/search/query_test.py
Labels: Upgrade Elasticsearch

#5126 Prepare for change to a single mapping type per index in Elasticsearch 6
  h/search/client.py
  h/search/config.py
  h/search/core.py
  h/search/index.py
  tests/h/indexer/reindexer_test.py
  tests/h/search/config_test.py
  tests/h/search/index_test.py
  tests/h/search/old_core_test.py
  tests/h/search/old_index_test.py
Labels: Upgrade Elasticsearch

#5144 Remove old `h.search.core` tests
  tests/h/search/core_test.py
  tests/h/search/old_core_test.py
Labels: Upgrade Elasticsearch

#5139 Add support for identities to user_signup service
  h/services/user_signup.py
  tests/h/services/user_signup_test.py
Labels: lms

#5106 Make existing queries compatible with Elasticsearch 6
  h/search/query.py
  tests/h/search/old_query_test.py
  tests/h/search/query_test.py
Labels: Upgrade Elasticsearch

#5122 Remove old Elasticsearch index after reindexing annotations
  h/indexer/reindexer.py
  h/search/config.py
  tests/h/indexer/reindexer_test.py
  tests/h/search/config_test.py
Labels: Upgrade Elasticsearch

#5140 Add annotation mapping for Elasticsearch 6
  h/search/config.py
  tests/h/cli/commands/search_test.py
  tests/h/search/config_test.py
Labels: Upgrade Elasticsearch

#5148 Add fetch by identity
  h/services/user.py
  tests/common/factories/__init__.py
  tests/common/factories/user_identity.py
  tests/h/services/user_test.py
Labels: lms

#5149 Add user unique(ness) service
  h/services/__init__.py
  h/services/user_unique.py
  tests/h/services/user_unique_test.py
Labels: lms

#5153 Rename `NipsaService.flagged_userids`
  h/services/nipsa.py
  h/views/admin_nipsa.py
  tests/h/services/nipsa_test.py
  tests/h/views/admin_nipsa_test.py
Labels: Upgrade Elasticsearch

#5162 Add Identities, 409 errors to `POST users/` endpoint
  docs/_extra/api-reference/hypothesis.yaml
  docs/_extra/api-reference/schemas/new-user-schema.json
  h/schemas/api/user.py
  h/views/api/users.py
  tests/h/schemas/api/user_test.py
  tests/h/views/api/users_test.py
Labels: API, lms

#5154 Speed up reindexing by re-adding NIPSA flag cache
  h/indexer/reindexer.py
  h/services/nipsa.py
  tests/h/indexer/reindexer_test.py
  tests/h/services/nipsa_test.py
Labels: Upgrade Elasticsearch

#5161 Index annotations into Elasticsearch 6 when feature flag enabled
  h/indexer/reindexer.py
  h/tasks/indexer.py
  tests/h/indexer/reindexer_test.py
  tests/h/tasks/indexer_test.py
Labels: Upgrade Elasticsearch

#5169 Update create-user API schema to require email OR valid identities
  docs/_extra/api-reference/schemas/new-user-schema.json
  h/schemas/api/user.py
  tests/h/schemas/api/user_test.py
Labels: API, lms

#5172 Run new search indexing tests against es1 and es6
  tests/common/fixtures/__init__.py
  tests/common/fixtures/elasticsearch.py
  tests/h/conftest.py
  tests/h/search/conftest.py
  tests/h/search/connection_test.py
  tests/h/search/index_test.py
Labels: Upgrade Elasticsearch

#5171 Add a partial index on the `user.nipsa` column
  h/migrations/versions/7fe5d688edd9_add_index_to_user_nipsa.py
  h/models/user.py
  h/services/nipsa.py
Labels: Upgrade Elasticsearch

#5175 Add `--es6` flag to `search reindex` CLI command
  h/cli/commands/search.py
  tests/h/cli/commands/search_test.py
Labels: Upgrade Elasticsearch

#5178 Ignore `ELASTICSEARCH_CLIENT_TIMEOUT` env var in `hypothesis init` command
  h/cli/commands/init.py
Labels: Upgrade Elasticsearch

#5176 Add search_es6 feature flag and run search tests against es6
  h/models/feature.py
  h/search/core.py
  tests/h/search/core_test.py
  tests/h/search/query_test.py
Labels: Upgrade Elasticsearch

#5196 Add AuthClientPolicy and supporting utils
  h/auth/policy.py
  h/auth/util.py
  tests/h/auth/policy_test.py
  tests/h/auth/util_test.py
Labels: lms

#5198 Add single functional test for creating a private group
  tests/functional/api/__init__.py
  tests/functional/api/test_groups.py
Labels: lms

#5199 Expand group API Functional Tests
  tests/functional/api/test_groups.py
Labels: lms
