Repository hypothesis/h, pull requests merged in 2018-04, with the labels that each got.

#4958 Fix serialization of custom OAuth errors to JSON
  h/oauth/errors.py
  tests/h/oauth/errors_test.py
Labels: pylint

#4960 2to3: Replace im_self with __self__
  h/websocket.py
Labels: Python 3000

#4969 Remove unnecessary urls and deprecated url properties from the groups
  docs/_extra/api-reference/schemas/group.yaml
  h/presenters/group_json.py
  tests/h/presenters/group_json_test.py
Labels: Do not merge
