Repository hypothesis/h, pull requests merged in 2018-08, with the labels that each got.

#5206 Add ClientAuthPolicy with ability to authenticate as a forwarded user
  h/auth/policy.py
  h/auth/util.py
  tests/h/auth/policy_test.py
  tests/h/auth/util_test.py
Labels: lms

#5217 Update Elasticsearch version and URL in installation docs
  docs/developing/install.rst
Labels: Upgrade Elasticsearch

#5240 Remove old search indexing tests
  tests/h/search/old_index_test.py
Labels: Upgrade Elasticsearch

#5223 Make Group.organization nullable and create new private groups with no organization
  h/migrations/versions/5d256923d642_make_organization_relation_nullable_on_.py
  h/models/group.py
  h/presenters/group_json.py
  h/services/group.py
  h/templates/admin/groups.html.jinja2
  h/traversal/contexts.py
  h/views/activity.py
  tests/h/presenters/group_json_test.py
  tests/h/services/group_test.py
  tests/h/traversal/contexts_test.py
  tests/h/views/activity_test.py
Labels: lms

#5239 Search indexing test cleanups
  tests/h/search/index_test.py
Labels: Upgrade Elasticsearch

#5229 Update API docs to indicate group.organization may be `null`
  docs/_extra/api-reference/schemas/group.yaml
Labels: API, lms

#5218 Use API Policy; Restrict AuthClientPolicy to `POST /api/groups`
  h/auth/__init__.py
  h/auth/policy.py
  h/views/api/groups.py
  tests/functional/api/test_groups.py
  tests/h/auth/policy_test.py
  tests/h/views/api/groups_test.py
Labels: API, lms

#5250 Remove remaining references to elasticsearch1 and elasticsearch1-dsl from config files
  conf/app.ini
  tox.ini
Labels: Upgrade Elasticsearch

#5252 Remove remaining es1 switch statement
  h/indexer/reindexer.py
Labels: Upgrade Elasticsearch

#5253 Move old Builder tests to query_test module
  tests/h/search/old_query_test.py
  tests/h/search/query_test.py
Labels: Upgrade Elasticsearch

#5247 Add helper for validating query parameters using colander
  h/schemas/util.py
  tests/h/schemas/util_test.py
Labels: Upgrade Elasticsearch

#5224 Ignore unknown es query params
  docs/_extra/api-reference/hypothesis.yaml
  h/schemas/annotation.py
  h/search/query.py
  h/views/api/annotations.py
  tests/h/schemas/annotation_test.py
  tests/h/schemas/util_test.py
  tests/h/search/query_test.py
  tests/h/views/api/annotations_test.py
Labels: Upgrade Elasticsearch
