Repository hypothesis/h, pull requests merged in 2018-11, with the labels that each got.

#5403 Refactor GroupCreateService to allow passing authority_provided_id
  h/services/group_create.py
  tests/h/services/group_create_test.py
Labels: WIP

#5405 Add rudimentary documentation for `groupid` in group responses
  docs/_extra/api-reference/schemas/group.yaml
Labels: lms

#5409 Add `groupid` setter to Group model
  h/models/group.py
  tests/h/models/group_test.py
Labels: lms

#5411 Add schema and POST endpoint support for `groupid`
  h/models/group.py
  h/schemas/api/group.py
  h/util/group.py
  h/views/api/groups.py
  tests/functional/api/test_groups.py
  tests/h/models/group_test.py
  tests/h/schemas/api/group_test.py
  tests/h/util/group_test.py
  tests/h/views/api/groups_test.py
Labels: lms

#5421 Refactor group API schema to support PATCH, PUT
  h/schemas/api/group.py
  tests/functional/api/test_groups.py
  tests/h/schemas/api/group_test.py
Labels: lms

#5424 Explicitly add userid principal for AuthClient forwarded users
  h/auth/util.py
  tests/h/auth/util_test.py
Labels: API, lms

#5425 Add `PATCH /api/groups/{id}` endpoint
  h/auth/policy.py
  h/routes.py
  h/views/api/groups.py
  tests/functional/api/groups/test_create.py
  tests/functional/api/groups/test_members.py
  tests/functional/api/groups/test_update.py
  tests/h/routes_test.py
  tests/h/views/api/groups_test.py
Labels: API, lms

#5428 Add `PUT /api/groups/{id}` endpoint
  h/auth/policy.py
  h/models/group.py
  h/routes.py
  h/views/api/groups.py
  tests/functional/api/groups/test_upsert.py
  tests/h/models/group_test.py
  tests/h/routes_test.py
  tests/h/views/api/groups_test.py
Labels: API, lms

#5430 Add documentation for group UPSERT
  docs/_extra/api-reference/hypothesis.yaml
Labels: API

#5437 Allow AuthClients to `PATCH groups/{id}` without Forwarded User
  docs/_extra/api-reference/hypothesis.yaml
  h/models/group.py
  tests/functional/api/groups/test_update.py
  tests/h/models/group_test.py
Labels: API, lms
