Repository hypothesis/h, pull requests merged in 2020-02, with the labels that each got.

#5906 Add missing "lang" attribute for sidebar HTML page
  h/templates/app.html.jinja2
Labels: Accessibility

#5905 Bulk API initial design
  docs/api/design/bulk-api/approach.md
  docs/api/design/bulk-api/index.md
  docs/api/design/bulk-api/research/current-api.md
  docs/api/design/bulk-api/research/mongo-upserts.md
  docs/api/design/bulk-api/schema/bulk_api/configuration.json
  docs/api/design/bulk-api/schema/bulk_api/examples/create_group_membership.json
  docs/api/design/bulk-api/schema/bulk_api/examples/job_configuration.json
  docs/api/design/bulk-api/schema/bulk_api/examples/upsert_group.json
  docs/api/design/bulk-api/schema/bulk_api/examples/upsert_user.json
  docs/api/design/bulk-api/schema/bulk_api/instruction.json
  docs/api/design/bulk-api/schema/check.py
  docs/api/design/bulk-api/schema/core.json
  docs/api/design/bulk-api/solutions/new-prob.md
  docs/api/design/bulk-api/solutions/referencing-items.md
  docs/api/design/bulk-api/solutions/representing-group-membership.md
  docs/api/design/bulk-api/solutions/representing-items.md
  docs/api/design/bulk-api/solutions/request-limits-and-pagination.md
  docs/api/design/bulk-api/solutions/request-structure.md
  docs/api/design/bulk-api/solutions/response-structure.md
  docs/api/design/bulk-api/solutions/specifying-actions.md
  docs/api/design/bulk-api/solutions/specifying-processing-instructions.md
  docs/api/design/bulk-api/solutions/specifying-upserts.md
  docs/api/design/bulk-api/summary.md
Labels: Spike, WIP, design

#5919 Move coverage from Travis to Jenkins
  .travis.yml
  Jenkinsfile
  scripts/elasticsearch.sh
Labels: bug

#5920 Inline schema examples and add new ones plus titles and descriptions
  h/h_api/resources/schema/bulk_api/command/configuration.json
  h/h_api/resources/schema/bulk_api/command/create_group_membership.json
  h/h_api/resources/schema/bulk_api/command/upsert_group.json
  h/h_api/resources/schema/bulk_api/command/upsert_user.json
  h/h_api/resources/schema/bulk_api/examples/configure.json
  h/h_api/resources/schema/bulk_api/examples/create_group_membership.json
  h/h_api/resources/schema/bulk_api/examples/upsert_group.json
  h/h_api/resources/schema/bulk_api/examples/upsert_user.json
  h/h_api/resources/schema/bulk_api/wrapper.json
  h/h_api/resources/schema/core.json
  h/h_api/resources/schema/json_api.json
Labels: technical enabler
