Repository hypothesis/h, pull requests merged in 2020-09, with the labels that each got.

#6184 Pin all requirements in requirements/ dir
  Dockerfile
  Makefile
  requirements.txt
  requirements/analyze.in
  requirements/analyze.txt
  requirements/coverage.in
  requirements/coverage.txt
  requirements/dev.in
  requirements/dev.txt
  requirements/dockercompose.in
  requirements/dockercompose.txt
  requirements/docs.in
  requirements/docs.txt
  requirements/format.in
  requirements/format.txt
  requirements/functests.in
  requirements/functests.txt
  requirements/lint.in
  requirements/lint.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/tests.in
  requirements/tests.txt
  tox.ini
Labels: technical debt

#6210 Emit caching headers for blocked badge requests
  h/views/badge.py
  tests/h/views/badge_test.py
Labels: enhancement

#6223 Fix pattern to allow to catch no slash and prevent Vary header
  h/views/badge.py
  tests/h/views/badge_test.py
Labels: bug

#6230 NewRelic - Updated configuration definition
  conf/supervisord.conf
Labels: operations, technical debt

#6224 Partially pre-compile the filter clause
  h/streamer/filter.py
  tests/h/streamer/filter_test.py
Labels: technical debt

#6231 Remove uni_fold normalisation and cache url normalisation on annotations
  .coveragerc
  h/streamer/filter.py
  h/streamer/messages.py
  tests/h/streamer/filter_test.py
Labels: technical debt

#6241 Move to a much simpler and faster socket filtering mechanism
  h/streamer/filter.py
  h/streamer/messages.py
  h/streamer/websocket.py
  tests/h/streamer/filter_test.py
  tests/h/streamer/messages_test.py
  tests/h/streamer/websocket_test.py
Labels: technical debt

#6242 Check to see if filter_rows have been added to sockets
  h/streamer/filter.py
  tests/h/streamer/filter_test.py
Labels: bug

#6244 Add `chrome://` schema URLs to the badge block list
  h/views/badge.py
  tests/h/views/badge_test.py
Labels: technical debt

#6245 Prevent unexpected values from causing the websocket filtering to crash
  h/streamer/filter.py
  tests/h/streamer/filter_test.py
Labels: bug

#6243 Remove an attempt to prevent the Vary: Cookie header that didn't work
  h/views/badge.py
Labels: technical debt

#6259 Removing indexing tests which look like they are testing something else
  tests/h/search/index_test.py
Labels: technical debt

#6279 Ensure we check the feature flag in a managed transaction
  h/subscribers.py
  tests/h/subscribers_test.py
Labels: bug
