Repository hypothesis/h, pull requests merged in 2021-08, with the labels that each got.

#6892 Move the root annotation permissions to `security.ACL`
  h/security/acl.py
  h/traversal/annotation.py
  tests/h/security/test_acl.py
  tests/h/traversal/annotation_test.py
Labels: technical debt

#6908 Remove the group finder service
  h/interfaces.py
  h/services/__init__.py
  h/services/groupfinder.py
  tests/common/fixtures/services.py
  tests/h/services/groupfinder_test.py
Labels: technical debt

#6916 Use the correct permission instead of the string
  h/streamer/messages.py
  tests/h/streamer/messages_test.py
Labels: bug

#6922 Fix tests which passed the wrong arguments to AnnotationContext
  tests/h/presenters/annotation_jsonld_test.py
  tests/h/traversal/annotation_test.py
  tests/h/views/main_test.py
Labels: bug

#6913 Merge remaining user permissions into `security.ACL`
  h/security/acl.py
  h/traversal/user.py
  tests/h/security/test_acl.py
  tests/h/traversal/user_test.py
Labels: technical debt

#6912 Rearrange the auth policy definitions to be less confusing
  h/auth/__init__.py
  h/streamer/app.py
Labels: technical debt

#6923 Remove the OAuthClients traversal
  h/routes.py
  h/traversal/__init__.py
  h/traversal/auth_client.py
  h/views/admin/oauthclients.py
  tests/h/routes_test.py
  tests/h/traversal/auth_client_test.py
  tests/h/views/admin/oauthclients_test.py
Labels: technical debt

#6925 Gut the annotation moderation service
  h/formatters/annotation_hidden.py
  h/models/annotation.py
  h/services/annotation_moderation.py
  h/views/api/moderation.py
  tests/h/models/annotation_test.py
  tests/h/services/annotation_moderation_test.py
  tests/h/views/api/moderation_test.py
Labels: technical debt

#6918 Add a separate docker image which only runs the Websocket
  Makefile
  conf/supervisord-dev.conf
  conf/websocket-dev.ini
  conf/websocket.ini
  h/streamer/Dockerfile
  h/streamer/conf/nginx.conf
  h/streamer/conf/supervisord.conf
  h/streamer/conf/websocket-dev.ini
  h/streamer/conf/websocket.ini
Labels: Spike, enhancement

#6945 Revert "Add a relationship between annotations and users"
  h/formatters/__init__.py
  h/formatters/annotation_flag.py
  h/formatters/annotation_hidden.py
  h/formatters/annotation_moderation.py
  h/formatters/annotation_user_info.py
  h/models/annotation.py
  h/models/user.py
  h/presenters/annotation_json.py
  h/services/annotation_json_presentation/_formatters/__init__.py
  h/services/annotation_json_presentation/factory.py
  h/services/annotation_json_presentation/service.py
  h/services/flag.py
  h/streamer/messages.py
  tests/h/formatters/__init__.py
  tests/h/formatters/annotation_flag_test.py
  tests/h/formatters/annotation_hidden_test.py
  tests/h/formatters/annotation_moderation_test.py
  tests/h/formatters/annotation_user_info_test.py
  tests/h/models/annotation_test.py
  tests/h/presenters/annotation_json_test.py
  tests/h/services/annotation_json_presentation_test/factory_test.py
  tests/h/services/annotation_json_presentation_test/service_test.py
  tests/h/services/flag_test.py
  tests/h/streamer/messages_test.py
Labels: bug

#6949 Move the user formatting inside the JSON presenter
  h/formatters/__init__.py
  h/formatters/annotation_user_info.py
  h/presenters/annotation_json.py
  h/services/annotation_json_presentation/service.py
  h/streamer/messages.py
  tests/h/formatters/annotation_user_info_test.py
  tests/h/presenters/annotation_json_test.py
  tests/h/services/annotation_json_presentation_test/service_test.py
  tests/h/streamer/messages_test.py
Labels: Backend

#6947 Move formatters to JSON service and away from the presenter (MKII)
  h/formatters/__init__.py
  h/presenters/annotation_json.py
  h/services/annotation_json_presentation/_formatters/__init__.py
  h/services/annotation_json_presentation/_formatters/flag.py
  h/services/annotation_json_presentation/_formatters/hidden.py
  h/services/annotation_json_presentation/_formatters/moderation.py
  h/services/annotation_json_presentation/service.py
  tests/h/formatters/annotation_flag_test.py
  tests/h/presenters/annotation_json_test.py
  tests/h/services/annotation_json_presentation_test/_formatters/__init__.py
  tests/h/services/annotation_json_presentation_test/_formatters/flag_test.py
  tests/h/services/annotation_json_presentation_test/_formatters/hidden_test.py
  tests/h/services/annotation_json_presentation_test/_formatters/moderation_test.py
  tests/h/services/annotation_json_presentation_test/service_test.py
Labels: technical debt

#6960 Move the roles to security as an Enum like class
  h/auth/role.py
  h/auth/util.py
  h/security/acl.py
  h/security/role.py
  tests/h/auth/util_test.py
  tests/h/security/test_acl.py
  tests/h/traversal/conftest.py
  tests/h/traversal/group_test.py
Labels: technical debt

#6961 Ensure we don't issue a query per annotation for moderation information
  h/services/annotation_json_presentation/service.py
  tests/h/services/annotation_json_presentation_test/service_test.py
Labels: technical debt, enhancement

#6919 Add config to try and build the websocket only image
  Jenkinsfile
Labels: Spike, enhancement

#6835 Fix pylint invalid-name
  .pylintrc
  h/_version.py
  h/accounts/schemas.py
  h/activity/query.py
  h/cli/commands/migrate.py
  h/cli/commands/move_uri.py
  h/cli/commands/normalize_uris.py
  h/cli/commands/search.py
  h/cli/commands/user.py
  h/db/types.py
  h/jinja_extensions.py
  h/models/auth_client.py
  h/models/document/_document.py
  h/models/group.py
  h/presenters/document_json.py
  h/presenters/document_searchindex.py
  h/schemas/base.py
  h/schemas/forms/accounts/login.py
  h/schemas/forms/admin/group.py
  h/search/index.py
  h/search/parser.py
  h/search/query.py
  h/services/feature.py
  h/services/links.py
  h/util/db.py
  h/util/document_claims.py
  h/util/markdown.py
  h/util/query.py
  h/util/redirects.py
  h/util/uri.py
  h/views/account_signup.py
  h/views/accounts.py
  h/views/activity.py
  h/views/admin/organizations.py
  h/views/admin/users.py
  h/views/api/config.py
  h/views/badge.py
  h/views/feeds.py
  h/views/main.py
  h/views/notification.py
  tests/h/util/markdown_test.py
Labels: Backend

#6966 Consolidate principal generation in `principals_for_identity`
  h/auth/policy.py
  h/security/principals.py
  tests/h/auth/policy_test.py
  tests/h/security/test_principals.py
Labels: technical debt
