Repository hypothesis/h, pull requests merged in 2021-07, with the labels that each got.

#6746 Ignore anything but minor updates for Python docker images
  .github/dependabot.yml
Labels: technical debt

#6756 Pull all org values to the org and eliminate duplications
  h/db/__init__.py
  h/models/organization.py
  h/schemas/forms/admin/organization.py
  h/traversal/contexts.py
  h/views/admin/organizations.py
  tests/h/conftest.py
  tests/h/models/organization_test.py
  tests/h/schemas/forms/admin/organization_test.py
  tests/h/views/admin/organizations_test.py
Labels: technical debt

#6757 Move the traversal `default()` to model `is_default()`
  h/models/organization.py
  h/presenters/organization_json.py
  h/traversal/contexts.py
  h/views/admin/organizations.py
  tests/h/models/organization_test.py
  tests/h/traversal/contexts_test.py
Labels: technical debt

#6728 Move organization default behavior from traversal and DB to service
  h/db/__init__.py
  h/models/organization.py
  h/services/organization.py
  h/views/admin/groups.py
  tests/h/models/organization_test.py
  tests/h/services/organization_test.py
Labels: technical debt

#6732 Move the organization resources to their own file
  h/traversal/__init__.py
  h/traversal/contexts.py
  h/traversal/organization.py
  h/traversal/roots.py
  tests/h/traversal/contexts_test.py
  tests/h/traversal/organization_test.py
  tests/h/traversal/roots_test.py
Labels: technical debt, technical enabler

#6748 Move and consolidate group related traversals
  h/traversal/__init__.py
  h/traversal/contexts.py
  h/traversal/group.py
  h/traversal/roots.py
  tests/common/fixtures/services.py
  tests/h/traversal/conftest.py
  tests/h/traversal/contexts_test.py
  tests/h/traversal/group_test.py
  tests/h/traversal/roots_test.py
  tests/h/views/api/groups_test.py
Labels: technical debt

#6749 Consolidate all annotation traversal into one file
  h/traversal/__init__.py
  h/traversal/annotation.py
  h/traversal/contexts.py
  h/traversal/roots.py
  tests/h/traversal/annotation_test.py
  tests/h/traversal/contexts_test.py
  tests/h/traversal/roots_test.py
Labels: technical debt

#6733 Remove the proxy to `pubid` called `id`
  h/presenters/group_json.py
  h/presenters/organization_json.py
  h/traversal/organization.py
  tests/h/presenters/group_json_test.py
  tests/h/presenters/organization_json_test.py
  tests/h/traversal/organization_test.py
Labels: technical debt, technical enabler

#6750 Consolidate user traversal objects
  h/traversal/__init__.py
  h/traversal/contexts.py
  h/traversal/roots.py
  h/traversal/user.py
  tests/h/traversal/contexts_test.py
  tests/h/traversal/roots_test.py
  tests/h/traversal/user_test.py
Labels: technical debt

#6751 Split the remaining traversal items into their own files
  h/traversal/__init__.py
  h/traversal/annotation.py
  h/traversal/auth_client.py
  h/traversal/bulk_api.py
  h/traversal/group.py
  h/traversal/organization.py
  h/traversal/profile.py
  h/traversal/root.py
  h/traversal/roots.py
  h/traversal/user.py
  tests/h/traversal/auth_client_test.py
  tests/h/traversal/bulk_api_test.py
  tests/h/traversal/profile_test.py
  tests/h/traversal/root_test.py
Labels: technical debt

#6761 Remove un-used `links()` property
  h/traversal/organization.py
  tests/h/traversal/organization_test.py
Labels: technical debt

#6762 Remove `OrganizationLogoRoot` by putting an `if` statement in the view
  h/routes.py
  h/traversal/__init__.py
  h/traversal/organization.py
  h/views/organizations.py
  tests/h/routes_test.py
  tests/h/traversal/organization_test.py
  tests/h/views/organizations_test.py
Labels: technical debt

#6763 Move organization lookup from the traversal to service
  h/services/organization.py
  h/traversal/organization.py
  tests/h/services/organization_test.py
  tests/h/traversal/organization_test.py
Labels: technical debt

#6731 Change from `logo()` to `logo_url()` for the org context
  h/presenters/organization_json.py
  h/traversal/organization.py
  h/views/activity.py
  tests/h/traversal/organization_test.py
Labels: technical debt

#6770 Increase the allowed open file handles for NGINX
  conf/nginx.conf
Labels: bug

#6771 Increase NGINX file limits to match the current hard limit
  conf/nginx.conf
Labels: bug

#6764 Refactor the group presenter to just be less weird
  h/presenters/group_json.py
Labels: technical debt

#6765 Remove the group context `id` property by calling pubid directly
  h/presenters/group_json.py
  h/traversal/group.py
  tests/h/traversal/group_test.py
Labels: technical debt

#6734 Use the organization context, not just the plain organization
  h/traversal/organization.py
  h/views/admin/organizations.py
  h/views/organizations.py
  tests/h/traversal/organization_test.py
  tests/h/views/admin/organizations_test.py
  tests/h/views/organizations_test.py
Labels: technical debt, technical enabler

#6786 Simplify the API groups view tests
  tests/common/fixtures/services.py
  tests/h/views/api/groups_test.py
Labels: technical debt

#6787 Use the group context instead of the group everywhere
  h/traversal/group.py
  h/views/activity.py
  h/views/admin/groups.py
  h/views/api/groups.py
  h/views/groups.py
  tests/h/traversal/group_test.py
  tests/h/views/activity_test.py
  tests/h/views/admin/groups_test.py
  tests/h/views/api/groups_test.py
  tests/h/views/groups_test.py
Labels: technical debt

#6838 Add product metadata to the `pyproject.toml` file
  pyproject.toml
Labels: enhancement

#6818 Use an Enum like class for Bulk API permissions
  h/security/permissions.py
  h/traversal/bulk_api.py
  h/views/api/bulk.py
  tests/h/traversal/bulk_api_test.py
Labels: technical debt

#6819 Use an Enum like class for profile permissions
  h/security/permissions.py
  h/traversal/profile.py
  h/views/api/profile.py
  tests/h/traversal/profile_test.py
Labels: technical debt

#6820 Use an Enum like class for user permissions
  h/models/user.py
  h/security/permissions.py
  h/traversal/user.py
  h/views/api/users.py
  tests/h/models/user_test.py
  tests/h/traversal/user_test.py
Labels: technical debt

#6821 Use an Enum like class for annotation permissions
  h/presenters/annotation_json.py
  h/security/permissions.py
  h/traversal/annotation.py
  h/views/api/annotations.py
  h/views/api/flags.py
  h/views/api/moderation.py
  h/views/main.py
  tests/h/streamer/contexts_test.py
  tests/h/traversal/annotation_test.py
  tests/h/views/api/auth_test.py
Labels: technical debt

#6841 Reduce the number of local variables in `reply_notifications.py`
  h/emails/reply_notification.py
Labels: technical debt

#6856 Refactor functests to have re-useable fixtures for being logged in
  tests/functional/conftest.py
  tests/functional/fixtures/__init__.py
  tests/functional/fixtures/authentication.py
  tests/functional/h/views/admin/test_permissions.py
Labels: technical debt, technical enabler

#6822 Use an Enum like class for group permissions
  h/formatters/annotation_moderation.py
  h/models/group.py
  h/security/permissions.py
  h/services/annotation_json_presentation.py
  h/storage.py
  h/traversal/annotation.py
  h/traversal/group.py
  h/views/activity.py
  h/views/admin/groups.py
  h/views/api/groups.py
  h/views/groups.py
  tests/h/formatters/annotation_moderation_test.py
  tests/h/models/group_test.py
  tests/h/presenters/annotation_json_test.py
  tests/h/services/annotation_json_presentation_test.py
  tests/h/traversal/annotation_test.py
  tests/h/traversal/group_test.py
  tests/h/views/activity_test.py
Labels: technical debt

#6855 Refactor the group ACL to be easier to understand
  h/models/group.py
Labels: technical debt

#6863 Split up the annotation JSON presentation service
  h/services/annotation_json_presentation/__init__.py
  h/services/annotation_json_presentation/factory.py
  h/services/annotation_json_presentation/service.py
  tests/h/services/annotation_json_presentation_test/__init__.py
  tests/h/services/annotation_json_presentation_test/factory_test.py
  tests/h/services/annotation_json_presentation_test/service_test.py
Labels: technical debt

#6864 Use common service fixtures and a single test for the factory
  h/services/annotation_json_presentation/factory.py
  tests/common/fixtures/services.py
  tests/h/services/annotation_json_presentation_test/factory_test.py
Labels: technical debt

#6861 Remove the annotation formatter interface
  h/formatters/__init__.py
  h/formatters/annotation_flag.py
  h/formatters/annotation_hidden.py
  h/formatters/annotation_moderation.py
  h/formatters/annotation_user_info.py
  h/formatters/formatter.py
  tests/h/presenters/annotation_json_test.py
Labels: technical debt

#6867 Use the correct annotation (not group) permission for moderation
  h/formatters/annotation_moderation.py
  tests/h/formatters/annotation_moderation_test.py
Labels: bug, technical debt

#6871 Use an enum for permissions collections
  h/security/permissions.py
Labels: technical debt

#6872 Some test coverage fixes
  .coveragerc
  tests/h/conftest.py
Labels: technical debt

#6870 Use the group context not the group for permission checks
  h/views/activity.py
Labels: technical debt

#6854 Fix pylint's no-self-use
  h/auth/policy.py
  h/models/group.py
  h/models/organization.py
  h/models/user.py
  h/realtime.py
  h/schemas/annotation.py
  h/schemas/api/group.py
  h/schemas/api/user.py
  h/schemas/base.py
  h/schemas/forms/accounts/reset_password.py
  h/search/query.py
  h/services/annotation_moderation.py
  h/services/delete_user.py
  h/services/developer_token.py
  h/services/group_create.py
  h/services/group_list.py
  h/services/oauth_provider.py
  h/services/search_index/service.py
  h/services/user.py
  h/util/markdown.py
  h/views/admin/search.py
Labels: Backend

#6836 Fix pylint too-many-try-statements
  h/accounts/schemas.py
  h/indexer/reindexer.py
  h/models/document/_document.py
  h/realtime.py
  h/schemas/annotation.py
  h/search/config.py
  h/search/query.py
  h/services/user.py
  h/streamer/db.py
  h/streamer/filter.py
  h/streamer/messages.py
  h/streamer/worker.py
  h/tasks/mailer.py
  h/views/admin/users.py
Labels: Backend

#6853 Fix pylint's inconsistent-return-statements
  h/auth/policy.py
  h/formatters/annotation_flag.py
  h/formatters/annotation_moderation.py
  h/models/annotation.py
  h/notification/reply.py
  h/presenters/annotation_base.py
  h/presenters/annotation_html.py
  h/search/query.py
  h/services/oauth_validator.py
  h/views/activity.py
Labels: Backend

#6884 Add fine grained assertions to debug flakey test
  tests/h/services/search_index/_queue_test.py
Labels: bug, technical debt

#6886 Hopefully fix the Queue test by making an order invariant comparison
  tests/h/services/search_index/_queue_test.py
Labels: bug

#6875 Use the group context to get ACLs not the group
  h/traversal/annotation.py
  tests/h/traversal/annotation_test.py
Labels: technical debt
