Repository hypothesis/h, pull requests merged in 2022-02, with the labels that each got.

#7261 Simplify our application of Markdown to allow it to be easily replaced
  h/util/markdown.py
Labels: technical debt, technical enabler

#7262 Rename the markdown module so it doesn't clash with `markdown`
  h/migrations/versions/d536d9a342f3_fill_in_annotation_text_rendered_column.py
  h/models/annotation.py
  h/util/markdown_render.py
  tests/h/models/annotation_test.py
  tests/h/util/markdown_render_test.py
Labels: technical enabler

#7278 Fix broken overflow for `pre code` content in activity-pages annotations
  h/static/styles/core/_typography.scss
Labels: frontend
